In [2]:
import numpy as np
np.random.rand(4,4)

array([[ 0.97823896,  0.73822039,  0.28921904,  0.56766275],
       [ 0.80985857,  0.4410576 ,  0.06286906,  0.69596154],
       [ 0.68501758,  0.16017242,  0.4099828 ,  0.65643093],
       [ 0.65859091,  0.82296421,  0.50443776,  0.84502195]])

In [3]:
rangMat = np.mat(np.random.rand(4, 4))

In [4]:
rangMat

matrix([[ 0.111055  ,  0.06147855,  0.41935833,  0.71759676],
        [ 0.08531922,  0.73121816,  0.29461722,  0.24497558],
        [ 0.20651452,  0.7245459 ,  0.02015982,  0.60787311],
        [ 0.43350734,  0.95248782,  0.72465909,  0.63615117]])

In [5]:
# 求逆
rangMat.I

matrix([[-2.1200814 , -5.31628859,  1.13232343,  3.35677362],
        [-0.50879792,  1.50092604,  0.33600652, -0.3251237 ],
        [ 0.79552778,  1.22825308, -1.93008785,  0.47392563],
        [ 1.3003328 , -0.02362398,  0.92390473, -0.76859742]])

In [6]:
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])